image: python:3.10-alpine
pages:
  tags:
    - pages
  stage: deploy
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    paths:
      - .cache/pip
      - .venv
  before_script:
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install -r requirements.txt
  script:
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
